# Generated by Django 2.2 on 2019-05-07 03:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('invoice_id', models.BigAutoField(db_column='INVOICE_ID', primary_key=True, serialize=False)),
                ('invoice_date', models.DateTimeField(blank=True, db_column='INVOICE_DATE', null=True)),
            ],
            options={
                'db_table': 'invoice',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Outlet',
            fields=[
                ('outlet_id', models.BigAutoField(db_column='OUTLET_ID', primary_key=True, serialize=False)),
                ('outlet_name', models.CharField(blank=True, db_column='OUTLET_NAME', max_length=255, null=True)),
                ('isdeleted', models.TextField(blank=True, db_column='isDeleted', null=True)),
            ],
            options={
                'db_table': 'outlet',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('product_number', models.CharField(db_column='PRODUCT_NUMBER', max_length=255, primary_key=True, serialize=False)),
                ('price', models.FloatField(blank=True, db_column='PRICE', null=True)),
                ('product_name', models.CharField(blank=True, db_column='PRODUCT_NAME', max_length=255, null=True)),
                ('isdeleted', models.TextField(blank=True, db_column='isDeleted', null=True)),
            ],
            options={
                'db_table': 'product',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.BigAutoField(db_column='ID', primary_key=True, serialize=False)),
                ('quantity', models.BigIntegerField(blank=True, db_column='QUANTITY', null=True)),
                ('outlet', models.ForeignKey(blank=True, db_column='OUTLET_ID', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='app.Outlet')),
                ('product_number', models.ForeignKey(blank=True, db_column='PRODUCT_NUMBER', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='app.Product')),
            ],
            options={
                'db_table': 'stock',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='InvoiceProduct',
            fields=[
                ('id', models.BigAutoField(db_column='ID', primary_key=True, serialize=False)),
                ('quantity', models.BigIntegerField(blank=True, db_column='QUANTITY', null=True)),
                ('invoice', models.ForeignKey(blank=True, db_column='INVOICE_ID', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='app.Invoice')),
                ('product_number', models.ForeignKey(blank=True, db_column='PRODUCT_NUMBER', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='app.Product')),
            ],
            options={
                'db_table': 'invoice_product',
                'managed': True,
            },
        ),
        migrations.AddField(
            model_name='invoice',
            name='outlet',
            field=models.ForeignKey(blank=True, db_column='OUTLET_ID', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='app.Outlet'),
        ),
    ]
