# Generated by Django 2.2 on 2019-05-10 04:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='outlet',
            name='isdeleted',
            field=models.TextField(blank=True, db_column='isDeleted', default=False, null=True),
        ),
    ]
